inveniosoftware/marshmallow-utils

CHANGES.rst, marshmallow_utils/fields/isodate.py, marshmallow_utils/version.py, tests/test_fields.py
=> 28 isodate tweak

CHANGES.rst, marshmallow_utils/fields/sanitizedhtml.py, marshmallow_utils/version.py, tests/test_fields.py
=> Fixed issue with empty lists

marshmallow_utils/fields/__init__.py, marshmallow_utils/fields/strippedhtml.py, marshmallow_utils/version.py, tests/test_fields.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/592
=> fields: add strippedHTML field

CHANGES.rst, marshmallow_utils/fields/__init__.py, marshmallow_utils/fields/tzdatetime.py, marshmallow_utils/version.py, tests/test_fields.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/741
=> fields: add UTCISODateString field

CHANGES.rst, marshmallow_utils/schemas/identifier.py, marshmallow_utils/version.py, tests/fields/test_identifier_field.py, tests/schemas/test_identifier_schema.py
closes https://github.com/inveniosoftware/marshmallow-utils/issues/34
=> identifier: allow unknown schemas

marshmallow_utils/schemas/identifier.py, tests/schemas/test_identifier_schema.py
closes https://github.com/inveniosoftware/marshmallow-utils/issues/37
This implementation changes the behavious of the previous and has much more strict validation. Why?
- If you are using this field to validate, it should actually validate (i.e. removes `allow_all` and similar implementation since for that there is no need to use this schema)
- Restricts the use cases, and forces the user to specify which schemes are allowed. Again, using this field means *validating* and therefore there must be some validation "rules" (schemes).
=> schemas: identifier scheme refactor

marshmallow_utils/schemas/identifier.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/961
=> fields: identifiers error validation

marshmallow_utils/schemas/identifier.py, tests/fields/test_identifier_field.py, tests/schemas/test_identifier_schema.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/962
=> schemas: change allowed identifiers structure

marshmallow_utils/schemas/identifier.py, tests/schemas/test_identifier_schema.py
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/367
=> schemas: adds error grouping for identifiers

.github/workflows/pypi-publish.yml, .tx/config, MANIFEST.in, marshmallow_utils/translations/de/LC_MESSAGES/messages.po, marshmallow_utils/translations/messages.pot, setup.cfg, setup.py
* Adds translation workflow
* pushed and created resources in [transifex](https://www.transifex.com/inveniosoftware/invenio/marshmallow-utils-messages/)
closes #9
=> i18n: integrate translation flow

babel.ini, marshmallow_utils/translations/messages.pot
* remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm#1664
=> i18n: extract messages

marshmallow_utils/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
=> i18n: add german translation

CHANGES.rst, marshmallow_utils/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
=> release: v0.7.0

CHANGES.rst, marshmallow_utils/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
=> release: v0.7.1

marshmallow_utils/fields/edtfdatestring.py, tests/test_edtfdatestring.py
originated by https://github.com/zenodo/rdm-project/issues/416
=> edtf: allow date and time values

CHANGES.rst, marshmallow_utils/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
=> release: v0.8.0

marshmallow_utils/html.py
- Removing class attribute to avoid potential security risks 
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have …
=> html: updating allowed html attributes

CHANGES.rst, marshmallow_utils/__init__.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license …
=> release: v0.9.1

marshmallow_utils/fields/babel.py
=> babel: better handling for missing locales in catalog

.github/workflows/tests.yml, marshmallow_utils/fields/__init__.py, marshmallow_utils/fields/edtfdatestring.py, tests/test_edtfdatestring.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/2012
* partially addesses https://github.com/inveniosoftware/invenio-rdm-records/issues/1978
=> date: add EDTFLevel2 validator
